### ISSUE TITLE
feat: Add Configuration File Support

### ISSUE THREAD

**Issue by berntpopp** [berntpopp/varvis-download#11]
### Description
Introduce support for a configuration file to allow users to specify default settings, reducing the need to provide all arguments via the command line.

### Solution
1. Support reading configuration from a `.config.json` or `.env` file.
2. Allow command line arguments to override configuration file settings.
3. Validate configuration file contents.

### Tasks
- [ ] Implement reading from a configuration file.
- [ ] Allow command line arguments to override config settings.
- [ ] Validate configuration file contents.
